package id.imperial.shop;

import net.milkbowl.vault.economy.Economy;
import org.bukkit.*;import org.bukkit.entity.Player;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.ItemMeta;import org.bukkit.persistence.PersistentDataType;
import java.text.NumberFormat;import java.util.*;

public final class ShopService {
    final ImperialShopPlugin plugin; final Economy economy; final NamespacedKey actionKey,itemKey,qtyKey; final Map<Material,Price> prices=new EnumMap<>(Material.class); final Map<String,List<Material>> cats=new LinkedHashMap<>();
    ShopService(ImperialShopPlugin p,Economy e){plugin=p;economy=e;actionKey=new NamespacedKey(p,"action");itemKey=new NamespacedKey(p,"item");qtyKey=new NamespacedKey(p,"quantity");reload();}
    void reload(){prices.clear();cats.clear();var pc=plugin.getConfig();var sec=pc.getConfigurationSection("prices");if(sec!=null)for(String k:sec.getKeys(false)){Material m=Material.matchMaterial(k);if(m!=null)prices.put(m,new Price(sec.getDouble(k+".buy"),sec.getDouble(k+".sell")));}var cs=pc.getConfigurationSection("categories");if(cs!=null)for(String id:cs.getKeys(false)){List<Material> ms=new ArrayList<>();for(String n:cs.getStringList(id+".items")){Material m=Material.matchMaterial(n);if(m!=null&&prices.containsKey(m)&&!ms.contains(m))ms.add(m);}cats.put(id,ms);}}
    String money(double v){return NumberFormat.getNumberInstance(new Locale(plugin.getConfig().getString("settings.locale","id-ID"))).format(v).replace(",00","").replace(".00","");}
    String pretty(Material m){return Arrays.stream(m.name().split("_")).map(x->x.substring(0,1)+x.substring(1).toLowerCase()).reduce((a,b)->a+" "+b).orElse(m.name());}
    ItemStack icon(Material m,String name,List<String> lore,String action,String item){ItemStack i=new ItemStack(m);ItemMeta meta=i.getItemMeta();meta.setDisplayName(name);meta.setLore(lore);meta.getPersistentDataContainer().set(actionKey,PersistentDataType.STRING,action);if(item!=null)meta.getPersistentDataContainer().set(itemKey,PersistentDataType.STRING,item);i.setItemMeta(meta);return i;}
    void openShop(Player p){Inventory inv=Bukkit.createInventory(null,54,"§b§lIMPERIAL SHOP");int slot=0;for(var e:cats.entrySet()){Material mat=plugin.getConfig().getMaterial("categories."+e.getKey()+".material");String name=ChatColor.translateAlternateColorCodes('&',plugin.getConfig().getString("categories."+e.getKey()+".name",e.getKey()));inv.setItem(slot++,icon(mat==null?Material.CHEST:mat,name,List.of("§7Click untuk membuka kategori."),"category",e.getKey()));if(slot%9==8)slot++;}inv.setItem(49,icon(Material.BARRIER,"§cTutup",List.of(),"close",null));p.openInventory(inv);}
    void openCategory(Player p,String cat){List<Material> list=cats.get(cat);if(list==null)return;Inventory inv=Bukkit.createInventory(null,54,"§b§lSHOP » "+cat);for(int n=0;n<list.size()&&n<45;n++){Material m=list.get(n);Price pr=prices.get(m);inv.setItem(n,icon(m,"§f§l"+pretty(m),List.of("§7Beli: §eRp "+money(pr.buy()),"§7Jual: §aRp "+money(pr.sell()),"","§aKlik untuk membeli"),"buy",m.name()));}inv.setItem(45,icon(Material.ARROW,"§eKembali",List.of(),"back",null));p.openInventory(inv);}
    void openSell(Player p){Inventory inv=Bukkit.createInventory(null,54,"§a§lSELL GUI");int slot=0;Set<Material> seen=new HashSet<>();for(ItemStack i:p.getInventory().getStorageContents()){if(i==null||i.getType().isAir()||!prices.containsKey(i.getType())||!seen.add(i.getType())||slot>=45)continue;Price pr=prices.get(i.getType());inv.setItem(slot++,icon(i.getType(),"§f§l"+pretty(i.getType()),List.of("§7Harga jual: §aRp "+money(pr.sell()),"§7Jumlah inventory: §f"+count(p,i.getType()),"","§aKlik untuk menjual semua item ini"),"sell",i.getType().name()));}inv.setItem(48,icon(Material.GOLD_INGOT,"§aJual Semua",List.of("§7Menjual semua item yang memiliki harga."),"sellall",null));inv.setItem(49,icon(Material.BARRIER,"§cTutup",List.of(),"close",null));inv.setItem(50,icon(Material.CHEST,"§eJual Item Tangan",List.of("§7Menjual seluruh stack di tangan."),"sellhand",null));p.openInventory(inv);}
    int count(Player p,Material m){int n=0;for(ItemStack i:p.getInventory().getStorageContents())if(i!=null&&i.getType()==m)n+=i.getAmount();return n;}
    double sellMaterial(Player p,Material m){Price pr=prices.get(m);if(pr==null)return 0;double total=0;for(int slot=0;slot<p.getInventory().getSize();slot++){ItemStack i=p.getInventory().getItem(slot);if(i==null||i.getType()!=m)continue;total+=pr.sell()*i.getAmount();p.getInventory().setItem(slot,null);}return total;}
    void openQuantity(Player p,Material m){Price pr=prices.get(m);if(pr==null)return;Inventory inv=Bukkit.createInventory(null,27,"§b§lBELI » "+pretty(m));inv.setItem(10,icon(Material.REDSTONE_TORCH,"§e-16",List.of(),"qty:-16",m.name()));inv.setItem(11,icon(Material.REDSTONE,"§e-1",List.of(),"qty:-1",m.name()));inv.setItem(13,icon(m,"§f§l64x",List.of("§7Harga: §eRp "+money(pr.buy()*64)),"buy:64",m.name()));inv.setItem(15,icon(Material.GLOWSTONE_DUST,"§a+1",List.of(),"qty:+1",m.name()));inv.setItem(16,icon(Material.GLOWSTONE,"§a+16",List.of(),"qty:+16",m.name()));inv.setItem(22,icon(Material.ARROW,"§eBeli 1x",List.of("§7Harga: §eRp "+money(pr.buy())),"buy:1",m.name()));inv.setItem(26,icon(Material.BARRIER,"§cKembali",List.of(),"backcat",m.name()));p.openInventory(inv);}
    boolean buy(Player p,Material m,int amount){Price pr=prices.get(m);if(pr==null||amount<1)return false;double total=pr.buy()*amount;if(!economy.has(p,total))return false;int space=space(p,m);if(space<amount)return false;EconomyResponse w=withdraw(p,total);if(!w.ok)return false;p.getInventory().addItem(new ItemStack(m,amount));return true;}
    private EconomyResponse withdraw(Player p,double a){var r=economy.withdrawPlayer(p,a);return new EconomyResponse(r.transactionSuccess());}
    int space(Player p,Material m){int s=0;for(ItemStack i:p.getInventory().getStorageContents())if(i==null||i.getType()==Material.AIR)s+=m.getMaxStackSize();else if(i.isSimilar(new ItemStack(m)))s+=m.getMaxStackSize()-i.getAmount();return s;}
    double sellHand(Player p){ItemStack i=p.getInventory().getItemInMainHand();if(i==null||i.getType().isAir())return 0;Price pr=prices.get(i.getType());if(pr==null)return 0;int n=i.getAmount();p.getInventory().setItemInMainHand(null);return pr.sell()*n;}
    double sellContents(Player p){double total=0;for(int slot=0;slot<p.getInventory().getSize();slot++){ItemStack i=p.getInventory().getItem(slot);if(i==null||i.getType().isAir())continue;Price pr=prices.get(i.getType());if(pr==null)continue;total+=pr.sell()*i.getAmount();p.getInventory().setItem(slot,null);}return total;}
    record Price(double buy,double sell){} record EconomyResponse(boolean ok){}
}